### ISSUE TITLE
Error when `/` is not writable

### ISSUE THREAD

**Issue by RafaelKr** [rekalogika/file-src#10]
We have a host system where `open_basedir` restrictions are set.
The PHP scripts can only access the Webroot and `/tmp`.

Now when creating a file (in this case via `FromHttpFoundationFileAdapter::adapt`) we get an error.

Probably it's related to these lines: https://github.com/rekalogika/file-src/blob/9c9d257f280fbc46c21740447b3be6025cc81bf3/packages/file/src/Repository/FilesystemRepository.php#L56-L63
So probably it's a good idea to make the root of the `FilesystemRepository::$localFilesystem` configurable.

This is the stack trace I got when creating a file:
```
[2024-02-23T21:50:25.593570+00:00] request.CRITICAL: Uncaught PHP Exception League\Flysystem\UnableToCreateDirectory: "Unable to create a directory at /. mkdir(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/var/www/vhosts/example.net/:/tmp/)" at /var/www/vhosts/example.net/httpdocs/vendor/league/flysystem/src/UnableToCreateDirectory.php line 18 {"exception":"[object] (League\\Flysystem\\UnableToCreateDirectory(code: 0): Unable to create a directory at /. mkdir(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/var/www/vhosts/example.net/:/tmp/) at /var/www/vhosts/example.net/httpdocs/vendor/league/flysystem/src/UnableToCreateDirectory.php:18)
[stacktrace]
#0 /var/www/vhosts/example.net/httpdocs/vendor/league/flysystem-local/LocalFilesystemAdapter.php(313): League\\Flysystem\\UnableToCreateDirectory::atLocation()
#1 /var/www/vhosts/example.net/httpdocs/vendor/league/flysystem-local/LocalFilesystemAdapter.php(97): League\\Flysystem\\Local\\LocalFilesystemAdapter->ensureDirectoryExists()
#2 /var/www/vhosts/example.net/httpdocs/vendor/league/flysystem-local/LocalFilesystemAdapter.php(87): League\\Flysystem\\Local\\LocalFilesystemAdapter->ensureRootDirectoryExists()
#3 /var/www/vhosts/example.net/httpdocs/vendor/rekalogika/file/src/Repository/FilesystemRepository.php(58): League\\Flysystem\\Local\\LocalFilesystemAdapter->__construct()
#4 /var/www/vhosts/example.net/httpdocs/vendor/rekalogika/file/src/File.php(78): Rekalogika\\File\\Repository\\FilesystemRepository::getLocalFilesystem()
#5 /var/www/vhosts/example.net/httpdocs/vendor/rekalogika/file-symfony-bridge/src/HttpFoundation/FromHttpFoundationFileAdapter.php(33): Rekalogika\\File\\File->__construct()
#6 /var/www/vhosts/example.net/httpdocs/vendor/rekalogika/file-symfony-bridge/src/HttpFoundation/FromHttpFoundationFileAdapter.php(43): Rekalogika\\File\\Bridge\\Symfony\\HttpFoundation\\FromHttpFoundationFileAdapter->__construct()
#7 /var/www/vhosts/example.net/httpdocs/src/Form/Application/FieldDefinition/FieldType/MediaFilePondType.php(94): Rekalogika\\File\\Bridge\\Symfony\\HttpFoundation\\FromHttpFoundationFileAdapter::adapt()
#8 /var/www/vhosts/example.net/httpdocs/vendor/symfony/event-dispatcher/EventDispatcher.php(220): App\\Form\\Application\\FieldDefinition\\FieldType\\MediaFilePondType->App\\Form\\Application\\FieldDefinition\\FieldType\\{closure}()
#9 /var/www/vhosts/example.net/httpdocs/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()
#10 /var/www/vhosts/example.net/httpdocs/vendor/symfony/event-dispatcher/ImmutableEventDispatcher.php(30): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()
#11 /var/www/vhosts/example.net/httpdocs/vendor/symfony/form/Form.php(482): Symfony\\Component\\EventDispatcher\\ImmutableEventDispatcher->dispatch()
#12 /var/www/vhosts/example.net/httpdocs/vendor/symfony/form/Form.php(499): Symfony\\Component\\Form\\Form->submit()
#13 /var/www/vhosts/example.net/httpdocs/vendor/symfony/form/Form.php(499): Symfony\\Component\\Form\\Form->submit()
#14 /var/www/vhosts/example.net/httpdocs/vendor/symfony/form/Extension/HttpFoundation/HttpFoundationRequestHandler.php(110): Symfony\\Component\\Form\\Form->submit()
#15 /var/www/vhosts/example.net/httpdocs/vendor/symfony/form/Form.php(420): Symfony\\Component\\Form\\Extension\\HttpFoundation\\HttpFoundationRequestHandler->handleRequest()
#16 /var/www/vhosts/example.net/httpdocs/vendor/craue/formflow-bundle/Form/FormFlow.php(892): Symfony\\Component\\Form\\Form->handleRequest()
#17 /var/www/vhosts/example.net/httpdocs/src/Controller/ApplicationFormController.php(268): Craue\\FormFlowBundle\\Form\\FormFlow->isValid()
#18 /var/www/vhosts/example.net/httpdocs/src/Controller/ApplicationFormController.php(165): App\\Controller\\ApplicationFormController->getFormRenderResponse()
#19 /var/www/vhosts/example.net/httpdocs/vendor/symfony/http-kernel/HttpKernel.php(181): App\\Controller\\ApplicationFormController->detail()
#20 /var/www/vhosts/example.net/httpdocs/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#21 /var/www/vhosts/example.net/httpdocs/vendor/symfony/http-kernel/Kernel.php(197): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#22 /var/www/vhosts/example.net/httpdocs/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\\Component\\HttpKernel\\Kernel->handle()
#23 /var/www/vhosts/example.net/httpdocs/vendor/autoload_runtime.php(29): Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner->run()
#24 /var/www/vhosts/example.net/httpdocs/public/index.php(5): require_once('...')
#25 {main}
"} []
```

**Comment by RafaelKr** [comment]
I can reproduce it locally when doing the following change to my `/etc/php/8.2/fpm/php.ini`:

```diff
- ;open_basedir = 
+ open_basedir = /home/myuser/coding/my-project/:/tmp/
```
(`/home/myuser/coding/my-project/` is pointing to the root directory of my Symfony project.)

Interestingly locally it throws even a bit earlier:
```
request.CRITICAL: Uncaught PHP Exception ErrorException: "Warning: is_dir(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/home/myuser/coding/my-project/:/tmp/)" at /home/myuser/coding/my-project/vendor/league/flysystem-local/LocalFilesystemAdapter.php line 298 {"exception":"[object] (ErrorException(code: 0): Warning: is_dir(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/home/myuser/coding/my-project/:/tmp/) at /home/myuser/coding/my-project/vendor/league/flysystem-local/LocalFilesystemAdapter.php:298)"} []
```

**Comment by RafaelKr** [comment]
Using `lazyRootCreation` seems to solve the problem.

```php
 return self::$localFilesystem = new LocalFilesystemDecorator( 
     new Filesystem( 
         new LocalFilesystemAdapter( 
             '/', 
             mimeTypeDetector: $mimeTypeDetector,
             lazyRootCreation: true
         ) 
     ) 
 ); 
```

Although currently my Images have no thumbnails anymore because `data-href` is not added on the HTML data element. So `imageMetadata` doesn't seem to be set correctly. I'm currently not sure why this is.

This works for me, but probably only because I use [`EmbeddedMetadata`](https://rekalogika.dev/file-bundle/replicating-metadata-in-entities):
```twig
{# {% if data.get('imageMetadata') %} #}
{% if entry.type.type == 'image' %}
    data-href="{{ entry|image_resize(1024)|temporary_url }}"
{% endif %}
```

**Comment by priyadi** [comment]
It seems a cleaner solution would be making our own customized `LocalFilesystemAdapter` that does not check for its root directory. I'll see what I can do.

**Comment by priyadi** [comment]
@RafaelKr should be fixed in https://github.com/rekalogika/file-src/pull/12

**Comment by RafaelKr** [comment]
@priyadi Updated via `composer update rekalogika/file:dev-main#c99461b -W` - works like a charm!

Thank you very much for that quick fix.

**Comment by RafaelKr** [comment]
@priyadi do you plan to do create a patch release for this or will it be included in the next minor release?
